apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hcloud-pricing-exporter.fullname" . }}
  labels:
    {{- include "hcloud-pricing-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hcloud-pricing-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "hcloud-pricing-exporter.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "hcloud-pricing-exporter.serviceAccountName" . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:v{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HCLOUD_TOKEN
              {{- if .Values.secret.create }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "hcloud-pricing-exporter.fullname" . }}
                  key: token
              {{- else if .Values.secret.file }}
              value: {{ printf "file:%s" .Values.secret.file }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.reference.name }}
                  key: {{ .Values.secret.reference.key }}
              {{- end }}
          ports:
            - name: http-metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http-metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: http-metrics
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
