{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.rbac.kind }}
metadata:
  name: {{ include "hcloud-pricing-exporter.fullname" . }}
  labels:
    {{- include "hcloud-pricing-exporter.labels" . | nindent 4 }}
{{- with .Values.rbac.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
